spring:

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: customer-service-group
      
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

application:
  name: customer-service

server:
  port: 8083

  
resilience4j.circuitbreaker:
  instances:
    authServiceClient:
      register-health-indicator: true
      sliding-window-size: 5
      minimum-number-of-calls: 3
      failure-rate-threshold: 50
      wait-duration-in-open-state: 5s
